powerdnsadmin/models/base.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()
domain_apikey = db.Table(
    'domain_apikey',
    db.Column('domain_id', db.Integer, db.ForeignKey('domain.id')),
    db.Column('apikey_id', db.Integer, db.ForeignKey('apikey.id')))

powerdnsadmin/models/domain_setting.py
import traceback

from flask import current_app

from .base import db


class DomainSetting(db.Model):
    __tablename__ = 'domain_setting'
    id = db.Column(db.Integer, primary_key=True)
    domain_id = db.Column(db.Integer, db.ForeignKey('domain.id'))
    domain = db.relationship('Domain', back_populates='settings')
    setting = db.Column(db.String(255), nullable=False)
    value = db.Column(db.String(255))

    def __init__(self, id=None, setting=None, value=None):
        self.id = id
        self.setting = setting
        self.value = value

    def __repr__(self):
        return '<DomainSetting {0} for {1}>'.format(setting, self.domain.name)

    def __eq__(self, other):
        return type(self) == type(other) and self.setting == other.setting

    def set(self, value):
        try:
            self.value = value
            db.session.commit()
            return True
        except Exception as e:
            current_app.logger.error(
                'Unable to set DomainSetting value. DETAIL: {0}'.format(e))
            current_app.logger.debug(traceback.format_exc())
            db.session.rollback()
            return False

powerdnsadmin/routes/base.py
import base64
from flask import render_template, url_for, redirect, session, request, current_app
from flask_login import LoginManager

from ..models.user import User

login_manager = LoginManager()


def handle_bad_request(e):
    return render_template('errors/400.html', code=400, message=e), 400


def handle_unauthorized_access(e):
    session['next'] = request.script_root + request.path
    return redirect(url_for('index.login'))


def handle_access_forbidden(e):
    return render_template('errors/403.html', code=403, message=e), 403


def handle_page_not_found(e):
    return render_template('errors/404.html', code=404, message=e), 404


def handle_internal_server_error(e):
    return render_template('errors/500.html', code=500, message=e), 500


def load_if_valid(user, method, src_ip, trust_user = False):
    try:
        auth = user.is_validate(method, src_ip, trust_user)
        if auth == False:
            return None
        else:
            # login_user(user, remember=False)
            return User.query.filter(User.id==user.id).first()
    except Exception as e:
        current_app.logger.error('Error: {0}'.format(e))
        return None


@login_manager.user_loader
def load_user(id):
    """
    This will be current_user
    """
    return User.query.get(int(id))


@login_manager.request_loader
def login_via_authorization_header_or_remote_user(request):
    # Try to login using Basic Authentication
    auth_header = request.headers.get('Authorization')
    if auth_header:
        auth_method = request.args.get('auth_method', 'LOCAL')
        auth_method = 'LDAP' if auth_method != 'LOCAL' else 'LOCAL'
        auth_header = auth_header.replace('Basic ', '', 1)
        try:
            auth_header = str(base64.b64decode(auth_header), 'utf-8')
            username, password = auth_header.split(":")
        except TypeError as e:
            return None

        user = User(username=username,
                    password=password,
                    plain_text_password=password)
        return load_if_valid(user, method=auth_method, src_ip=request.remote_addr)
    
    # Try login by checking a REMOTE_USER environment variable
    remote_user = request.remote_user
    if remote_user and current_app.config.get('REMOTE_USER_ENABLED'):
        session_remote_user = session.get('remote_user')
        
        # If we already validated a remote user against an authorization method
        # a local user should have been created in the database, so we force a 'LOCAL' auth_method
        auth_method = 'LOCAL' if session_remote_user else current_app.config.get('REMOTE_AUTH_METHOD', 'LDAP') 
        current_app.logger.debug(
            'REMOTE_USER environment variable found: attempting {0} authentication for username "{1}"'
            .format(auth_method, remote_user))
        user = User(username=remote_user.strip())
        valid_remote_user = load_if_valid(user, method=auth_method, src_ip=request.remote_addr, trust_user=True)
        
        if valid_remote_user:
            # If we were successful in authenticating a trusted remote user, store it in session
            session['remote_user'] = valid_remote_user.username

        return valid_remote_user

    return None

powerdnsadmin/routes/dashboard.py
import datetime
from flask import Blueprint, render_template, url_for, current_app, request, jsonify, redirect, g, session
from flask_login import login_required, current_user, login_manager
from sqlalchemy import not_

from ..decorators import operator_role_required
from ..lib.utils import customBoxes
from ..models.user import User, Anonymous
from ..models.account import Account
from ..models.account_user import AccountUser
from ..models.domain import Domain
from ..models.domain_user import DomainUser
from ..models.setting import Setting
from ..models.history import History
from ..models.server import Server
from ..models.base import db

dashboard_bp = Blueprint('dashboard',
                         __name__,
                         template_folder='templates',
                         url_prefix='/dashboard')


@dashboard_bp.before_request
def before_request():
    # Check if user is anonymous
    g.user = current_user
    login_manager.anonymous_user = Anonymous

    # Check site is in maintenance mode
    maintenance = Setting().get('maintenance')
    if maintenance and current_user.is_authenticated and current_user.role.name not in [
            'Administrator', 'Operator'
    ]:
        return render_template('maintenance.html')

    # Manage session timeout
    session.permanent = True
    current_app.permanent_session_lifetime = datetime.timedelta(
        minutes=int(Setting().get('session_timeout')))
    session.modified = True


@dashboard_bp.route('/domains-custom/<path:boxId>', methods=['GET'])
@login_required
def domains_custom(boxId):
    if current_user.role.name in ['Administrator', 'Operator']:
        domains = Domain.query
    else:
        # Get query for domain to which the user has access permission.
        # This includes direct domain permission AND permission through
        # account membership
        domains = db.session.query(Domain) \
            .outerjoin(DomainUser, Domain.id == DomainUser.domain_id) \
            .outerjoin(Account, Domain.account_id == Account.id) \
            .outerjoin(AccountUser, Account.id == AccountUser.account_id) \
            .filter(
                db.or_(
                    DomainUser.user_id == current_user.id,
                    AccountUser.user_id == current_user.id
                ))

    template = current_app.jinja_env.get_template("dashboard_domain.html")
    render = template.make_module(vars={"current_user": current_user, "allow_user_view_history": Setting().get('allow_user_view_history')})

    columns = [
        Domain.name, Domain.dnssec, Domain.type, Domain.serial, Domain.master,
        Domain.account_id
    ]

    order_by = []
    for i in range(len(columns)):
        column_index = request.args.get("order[{0}][column]".format(i))
        sort_direction = request.args.get("order[{0}][dir]".format(i))
        if column_index is None:
            break
        if sort_direction != "asc" and sort_direction != "desc":
            sort_direction = "asc"

        column = columns[int(column_index)]
        order_by.append(getattr(column, sort_direction)())

    if order_by:
        domains = domains.order_by(*order_by)

    if boxId == "reverse":
        for boxId in customBoxes.order:
            if boxId == "reverse": continue
            domains = domains.filter(
                not_(Domain.name.ilike(customBoxes.boxes[boxId][1])))
    else:
        domains = domains.filter(Domain.name.ilike(
            customBoxes.boxes[boxId][1]))

    total_count = domains.count()

    search = request.args.get("search[value]")
    if search:
        start = "" if search.startswith("^") else "%"
        end = "" if search.endswith("$") else "%"

        if current_user.role.name in ['Administrator', 'Operator']:
            domains = domains.outerjoin(Account).filter(
                Domain.name.ilike(start + search.strip("^$") + end)
                | Account.name.ilike(start + search.strip("^$") + end)
                | Account.description.ilike(start + search.strip("^$") + end))
        else:
            domains = domains.filter(
                Domain.name.ilike(start + search.strip("^$") + end))

    filtered_count = domains.count()

    start = int(request.args.get("start", 0))
    length = min(int(request.args.get("length", 0)), 100)

    if length != -1:
        domains = domains[start:start + length]

    data = []
    for domain in domains:
        data.append([
            render.name(domain),
            render.dnssec(domain),
            render.type(domain),
            render.serial(domain),
            render.master(domain),
            render.account(domain),
            render.actions(domain),
        ])

    response_data = {
        "draw": int(request.args.get("draw", 0)),
        "recordsTotal": total_count,
        "recordsFiltered": filtered_count,
        "data": data,
    }
    return jsonify(response_data)


@dashboard_bp.route('/', methods=['GET', 'POST'])
@login_required
def dashboard():
    if not Setting().get('pdns_api_url') or not Setting().get(
            'pdns_api_key') or not Setting().get('pdns_version'):
        return redirect(url_for('admin.setting_pdns'))

    BG_DOMAIN_UPDATE = Setting().get('bg_domain_updates')
    if not BG_DOMAIN_UPDATE:
        current_app.logger.info('Updating domains in foreground...')
        Domain().update()
    else:
        current_app.logger.info('Updating domains in background...')

    show_bg_domain_button = BG_DOMAIN_UPDATE
    if BG_DOMAIN_UPDATE and current_user.role.name not in ['Administrator', 'Operator']:
        show_bg_domain_button = False

    # Stats for dashboard
    domain_count = 0
    history_number = 0
    history = []
    user_num = User.query.count()
    if current_user.role.name in ['Administrator', 'Operator']:
        domain_count = Domain.query.count()
        history_number = History.query.count()
        history = History.query.order_by(History.created_on.desc()).limit(4).all()
    elif Setting().get('allow_user_view_history'):
        history = db.session.query(History) \
            .join(Domain, History.domain_id == Domain.id) \
            .outerjoin(DomainUser, Domain.id == DomainUser.domain_id) \
            .outerjoin(Account, Domain.account_id == Account.id) \
            .outerjoin(AccountUser, Account.id == AccountUser.account_id) \
            .order_by(History.created_on.desc()) \
            .filter(
            db.or_(
                DomainUser.user_id == current_user.id,
                AccountUser.user_id == current_user.id
            )).all()
        history_number = len(history)  # history.count()
        history = history[:4]
        domain_count = db.session.query(Domain) \
            .outerjoin(DomainUser, Domain.id == DomainUser.domain_id) \
            .outerjoin(Account, Domain.account_id == Account.id) \
            .outerjoin(AccountUser, Account.id == AccountUser.account_id) \
            .filter(
                db.or_(
                    DomainUser.user_id == current_user.id,
                    AccountUser.user_id == current_user.id
                )).count()

    from .admin import convert_histories, DetailedHistory
    detailedHistories = convert_histories(history)
    
    server = Server(server_id='localhost')
    statistics = server.get_statistic()
    if statistics:
        uptime = list([
            uptime for uptime in statistics if uptime['name'] == 'uptime'
        ])[0]['value']
    else:
        uptime = 0

    # Add custom boxes to render_template
    return render_template('dashboard.html',
                           custom_boxes=customBoxes,
                           domain_count=domain_count,
                           user_num=user_num,
                           history_number=history_number,
                           uptime=uptime,
                           histories=detailedHistories,
                           show_bg_domain_button=show_bg_domain_button,
                           pdns_version=Setting().get('pdns_version'))


@dashboard_bp.route('/domains-updater', methods=['GET', 'POST'])
@login_required
@operator_role_required
def domains_updater():
    current_app.logger.debug('Update domains in background')
    d = Domain().update()

    response_data = {
        "result": d,
    }
    return jsonify(response_data)

powerdnsadmin/routes/user.py
import datetime
from flask import Blueprint, request, render_template, make_response, jsonify, redirect, url_for, g, session, current_app
from flask_login import current_user, login_required, login_manager

from ..models.user import User, Anonymous
from ..models.setting import Setting

user_bp = Blueprint('user',
                    __name__,
                    template_folder='templates',
                    url_prefix='/user')


@user_bp.before_request
def before_request():
    # Check if user is anonymous
    g.user = current_user
    login_manager.anonymous_user = Anonymous

    # Check site is in maintenance mode
    maintenance = Setting().get('maintenance')
    if maintenance and current_user.is_authenticated and current_user.role.name not in [
            'Administrator', 'Operator'
    ]:
        return render_template('maintenance.html')

    # Manage session timeout
    session.permanent = True
    current_app.permanent_session_lifetime = datetime.timedelta(
        minutes=int(Setting().get('session_timeout')))
    session.modified = True


@user_bp.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    if request.method == 'GET':
        return render_template('user_profile.html')
    if request.method == 'POST':
        if session['authentication_type'] == 'LOCAL':
            firstname = request.form.get('firstname', '').strip()
            lastname = request.form.get('lastname', '').strip()
            email = request.form.get('email', '').strip()
            new_password = request.form.get('password', '')
        else:
            firstname = lastname = email = new_password = ''
            current_app.logger.warning(
                'Authenticated externally. User {0} information will not allowed to update the profile'
                .format(current_user.username))

        if request.data:
            jdata = request.json
            data = jdata['data']
            if jdata['action'] == 'enable_otp':
                if session['authentication_type'] in ['LOCAL', 'LDAP']:
                    enable_otp = data['enable_otp']
                    user = User(username=current_user.username)
                    user.update_profile(enable_otp=enable_otp)
                    return make_response(
                        jsonify({
                            'status':
                            'ok',
                            'msg':
                            'Change OTP Authentication successfully. Status: {0}'
                            .format(enable_otp)
                        }), 200)
                else:
                    return make_response(
                        jsonify({
                            'status':
                            'error',
                            'msg':
                            'User {0} is externally. You are not allowed to update the OTP'
                            .format(current_user.username)
                        }), 400)

        user = User(username=current_user.username,
                    plain_text_password=new_password,
                    firstname=firstname,
                    lastname=lastname,
                    email=email,
                    reload_info=False)
        user.update_profile()

        return render_template('user_profile.html')


@user_bp.route('/qrcode')
@login_required
def qrcode():
    if not current_user:
        return redirect(url_for('index'))

    return current_user.get_qrcode_value(), 200, {
        'Content-Type': 'image/svg+xml',
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0'
    }

powerdnsadmin/templates/admin_edit_account.html
{% extends "base.html" %}
{% set active_page = "admin_accounts" %}
{% block title %}<title>Edit Account - {{ SITE_NAME }}</title>{% endblock %}

{% block dashboard_stat %}
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Account
        <small>{% if create %}New account{% else %}{{ account.name }}{% endif %}</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ url_for('dashboard.dashboard') }}"><i class="fa fa-dashboard"></i>Home</a></li>
        <li><a href="{{ url_for('admin.manage_account') }}">Accounts</a></li>
        <li class="active">{% if create %}Add{% else %}Edit{% endif %} account</li>
    </ol>
</section>
{% endblock %}

{% block content %}
<section class="content">
    <div class="row">
        <div class="col-md-4">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">{% if create %}Add{% else %}Edit{% endif %} account</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form role="form" method="post"
                    action="{% if create %}{{ url_for('admin.edit_account') }}{% else %}{{ url_for('admin.edit_account', account_name=account.name) }}{% endif %}">
                    <input type="hidden" name="_csrf_token" value="{{ csrf_token() }}">
                    <input type="hidden" name="create" value="{{ create }}">
                    <div class="box-body">
                        {% if error %}
                        <div class="alert alert-danger alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <h4><i class="icon fa fa-ban"></i> Error!</h4>
                            {{ error }}
                        </div>
                        <span class="help-block">{{ error }}</span>
                        {% endif %}
                        <div
                            class="form-group has-feedback {% if invalid_accountname or duplicate_accountname %}has-error{% endif %}">
                            <label class="control-label" for="accountname">Name</label>
                            <input type="text" class="form-control" placeholder="Account Name (required)"
                                name="accountname" {% if account %}value="{{ account.name }}" {% endif %}
                                {% if not create %}disabled{% endif %}>
                            <span class="fa fa-cog form-control-feedback"></span>
                            {% if invalid_accountname %}
                            <span class="help-block">Cannot be blank and must only contain alphanumeric
                                characters.</span>
                            {% elif duplicate_accountname %}
                            <span class="help-block">Account name already in use.</span>
                            {% endif %}
                        </div>
                        <div class="form-group has-feedback">
                            <label class="control-label" for="accountdescription">Description</label>
                            <input type="text" class="form-control" placeholder="Account Description (optional)"
                                name="accountdescription" {% if account %}value="{{ account.description }}" {% endif %}>
                            <span class="fa fa-industry form-control-feedback"></span>
                        </div>
                        <div class="form-group has-feedback">
                            <label class="control-label" for="accountcontact">Contact Person</label>
                            <input type="text" class="form-control" placeholder="Contact Person (optional)"
                                name="accountcontact" {% if account %}value="{{ account.contact }}" {% endif %}>
                            <span class="fa fa-user form-control-feedback"></span>
                        </div>
                        <div class="form-group has-feedback">
                            <label class="control-label" for="accountmail">Mail Address</label>
                            <input type="email" class="form-control" placeholder="Mail Address (optional)"
                                name="accountmail" {% if account %}value="{{ account.mail }}" {% endif %}>
                            <span class="fa fa-envelope form-control-feedback"></span>
                        </div>
                    </div>
                    <div class="box-header with-border">
                        <h3 class="box-title">Access Control</h3>
                    </div>
                    <div class="box-body">
                        <p>Users on the right have access to manage records in all domains
                            associated with the account.</p>
                        <p>Click on users to move between columns.</p>
                        <div class="form-group col-xs-2">
                            <select multiple="multiple" class="form-control" id="account_multi_user"
                                name="account_multi_user">
                                {% for user in users %}
                                <option {% if user.id in account_user_ids|default([]) %}selected{% endif %}
                                    value="{{ user.username }}">{{ user.username }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="box-footer">
                        <button type="submit"
                            class="btn btn-flat btn-primary">{% if create %}Create{% else %}Update{% endif %}
                            Account</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-md-8">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Help with creating a new account</h3>
                </div>
                <div class="box-body">
                    <p>
                        An account allows grouping of domains belonging to a particular entity, such as a customer or
                        department.<br />
                        A domain can be assigned to an account upon domain creation or through the domain administration
                        page.
                    </p>
                    <p>Fill in all the fields to the in the form to the left.</p>
                    <p>
                        <strong>Name</strong> is an account identifier. It will be stored as all lowercase letters (no
                        spaces, special characters etc).<br />
                        <strong>Description</strong> is a user friendly name for this account.<br />
                        <strong>Contact person</strong> is the name of a contact person at the account.<br />
                        <strong>Mail Address</strong> is an e-mail address for the contact person.
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block extrascripts %}
<script>
    $("#account_multi_user").multiSelect({
        selectableHeader: "<input type='text' class='search-input' autocomplete='off' placeholder='Username'>",
        selectionHeader: "<input type='text' class='search-input' autocomplete='off' placeholder='Username'>",
        afterInit: function (ms) {
            var that = this,
                $selectableSearch = that.$selectableUl.prev(),
                $selectionSearch = that.$selectionUl.prev(),
                selectableSearchString = '#' + that.$container.attr('id') + ' .ms-elem-selectable:not(.ms-selected)',
                selectionSearchString = '#' + that.$container.attr('id') + ' .ms-elem-selection.ms-selected';

            that.qs1 = $selectableSearch.quicksearch(selectableSearchString)
                .on('keydown', function (e) {
                    if (e.which === 40) {
                        that.$selectableUl.focus();
                        return false;
                    }
                });

            that.qs2 = $selectionSearch.quicksearch(selectionSearchString)
                .on('keydown', function (e) {
                    if (e.which == 40) {
                        that.$selectionUl.focus();
                        return false;
                    }
                });
        },
        afterSelect: function () {
            this.qs1.cache();
            this.qs2.cache();
        },
        afterDeselect: function () {
            this.qs1.cache();
            this.qs2.cache();
        }
    });
</script>
{% endblock %}

powerdnsadmin/templates/admin_manage_account.html
{% extends "base.html" %}
{% set active_page = "admin_accounts" %}
{% block title %}
<title>Account Management - {{ SITE_NAME }}</title>
{% endblock %} {% block dashboard_stat %}
<section class="content-header">
    <h1>
        Accounts <small>Manage accounts</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ url_for('dashboard.dashboard') }}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Accounts</li>
    </ol>
</section>
{% endblock %} {% block content %}
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Account Management</h3>
                </div>
                <div class="box-body">
                    <a href="{{ url_for('admin.edit_account') }}">
                        <button type="button" class="btn btn-flat btn-primary pull-left button_add_account">
                            Add Account&nbsp;<i class="fa fa-plus"></i>
                        </button>
                    </a>
                </div>
                <div class="box-body">
                    <table id="tbl_accounts" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Description</th>
                                <th>Contact</th>
                                <th>Mail</th>
                                <th>Member</th>
                                <th>Domain</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for account in accounts %}
                            <tr class="odd gradeX">
                                <td>{{ account.name }}</td>
                                <td>{{ account.description }}</td>
                                <td>{{ account.contact }}</td>
                                <td>{{ account.mail }}</td>
                                <td>{{ account.user_num }}</td>
                                <td>{{ account.domains|length }}</td>
                                <td width="15%">
                                    <button type="button" class="btn btn-flat btn-success"
                                        onclick="window.location.href='{{ url_for('admin.edit_account', account_name=account.name) }}'">
                                        Edit&nbsp;<i class="fa fa-cog"></i>
                                    </button>
                                    <button type="button" class="btn btn-flat btn-danger button_delete"
                                        id="{{ account.name }}">
                                        Delete&nbsp;<i class="fa fa-trash"></i>
                                    </button>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
{% endblock %}
{% block extrascripts %}
<script>
    // set up accounts data table
    $("#tbl_accounts").DataTable({
        "paging": true,
        "lengthChange": true,
        "searching": true,
        "ordering": true,
        "columnDefs": [{
            "orderable": false,
            "targets": [-1]
        }],
        "info": false,
        "autoWidth": false,
        "lengthMenu": [
            [10, 25, 50, 100, -1],
            [10, 25, 50, 100, "All"]
        ],
        "pageLength": 10
    });

    // handle deletion of account
    $(document.body).on('click', '.button_delete', function () {
        var modal = $("#modal_delete");
        var accountname = $(this).prop('id');
        var info = "Are you sure you want to delete " + accountname + "?";
        modal.find('.modal-body p').text(info);
        modal.find('#button_delete_confirm').click(function () {
            var postdata = {
                'action': 'delete_account',
                'data': accountname,
                '_csrf_token': '{{ csrf_token() }}'
            }
            applyChanges(postdata, $SCRIPT_ROOT + '/admin/manage-account', false, true);
            modal.modal('hide');
        })
        modal.modal('show');
    });
</script>
{% endblock %}
{% block modals %}
<div class="modal fade modal-warning" id="modal_delete">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Confirmation</h4>
            </div>
            <div class="modal-body">
                <p></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-flat btn-default pull-left" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-flat btn-danger" id="button_delete_confirm">Delete</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
{% endblock %}

powerdnsadmin/templates/dyndns.html
{{ response }}